const FETCH_USER_CREATE_START = '[user_create]/FETCH_USER_CREATE_START';
const FETCH_USER_CREATE_SUCCESS = '[user_create]/FETCH_USER_CREATE_SUCCESS';
const FETCH_USER_CREATE_FAILED = '[user_create]/FETCH_USER_CREATE_FAILED';

export default {
    FETCH_USER_CREATE_START,
    FETCH_USER_CREATE_SUCCESS,
    FETCH_USER_CREATE_FAILED
}