const FETCH_USER_EDIT_START = '[user_edit]/FETCH_USER_EDIT_START';
const FETCH_USER_EDIT_SUCCESS = '[user_edit]/FETCH_USER_EDIT_SUCCESS';
const FETCH_USER_EDIT_FAILED = '[user_edit]/FETCH_USER_EDIT_FAILED';

const FETCH_USER_GET_BEFORE_EDIT_START = '[user_edit]/FETCH_USER_GET_BEFORE_EDIT_START';
const FETCH_USER_GET_BEFORE_EDIT_SUCCESS = '[user_edit]/FETCH_USER_GET_BEFORE_EDIT_SUCCESS';
const FETCH_USER_GET_BEFORE_EDIT_FAILED = '[user_edit]/FETCH_USER_GET_BEFORE_EDIT_FAILED';

export default {
    FETCH_USER_EDIT_START,
    FETCH_USER_EDIT_SUCCESS,
    FETCH_USER_EDIT_FAILED,
    FETCH_USER_GET_BEFORE_EDIT_START,
    FETCH_USER_GET_BEFORE_EDIT_SUCCESS,
    FETCH_USER_GET_BEFORE_EDIT_FAILED,
}