const FETCH_USERS_START = '[users]/FETCH_USERS_START';
const FETCH_USERS_SUCCESS = '[users]/FETCH_USERS_SUCCESS';
const FETCH_USERS_FAILED = '[users]/FETCH_USERS_FAILED';

export default {
    FETCH_USERS_START, FETCH_USERS_SUCCESS,
    FETCH_USERS_FAILED
}