const FETCH_USER_DELETE_START = '[user_delete]/FETCH_USER_DELETE_START';
const FETCH_USER_DELETE_SUCCESS = '[user_delete]/FETCH_USER_DELETE_SUCCESS';
const FETCH_USER_DELETE_FAILED = '[user_delete]/FETCH_USER_DELETE_FAILED';

export default {
    FETCH_USER_DELETE_START,
    FETCH_USER_DELETE_SUCCESS,
    FETCH_USER_DELETE_FAILED
}